<?php
return [
    'navigation_group' => 'Research & Analysis', 'financial_reports' => 'Financial Reports', 'financial_report' => 'Financial Report',
    'company' => 'Company', 'stock' => 'Stock', 'stock_symbol' => 'Stock Symbol', 'periods' => 'Financial Periods', 'current_period' => 'Current Period', 'base_period' => 'Base Period', 'period_type' => 'Period Type', 'period_year' => 'Year', 'period_month' => 'Month', 'period_title' => 'Period Title',
    'financial_metrics' => 'Financial Metrics', 'revenue' => 'Revenue', 'gross_profit' => 'Gross Profit', 'net_profit' => 'Net Profit', 'eps' => 'Earnings Per Share (EPS)', 'analyst_note' => 'Analyst Note', 'coverage' => 'Coverage', 'net_profit_coverage' => 'Net Profit Coverage',
    'projection' => 'Annual Projection', 'enable_projection' => 'Enable Projection', 'projection_multiplier' => 'Projection Multiplier', 'projected' => 'Projected', 'summary_notes' => 'Summary Analysis', 'additional_kpis' => 'Additional KPIs',
    'operating_profit' => 'Operating Profit', 'operating_margin' => 'Operating Margin', 'net_margin' => 'Net Margin', 'book_value' => 'Book Value', 'cash_balance' => 'Cash Balance', 'total_assets' => 'Total Assets', 'total_liabilities' => 'Total Liabilities', 'shareholders_equity' => 'Shareholders Equity', 'item' => 'Item', 'print' => 'Print', 'download_image' => 'Download Image', 'download_image_failed' => 'Unable to create the report image. Please try again.', 'created' => 'Created',
    'top_growing_companies' => 'Top Growing Companies', 'highest_eps_growth' => 'Highest EPS Growth', 'latest_financial_reports' => 'Latest Financial Reports', 'best_coverage' => 'Best Coverage', 'dashboard_heading' => 'Financial Research Highlights', 'no_reports' => 'No reports yet', 'total_reports' => 'Total Reports', 'all_financial_reports' => 'All financial reports', 'companies_covered' => 'Companies Covered', 'unique_stocks' => 'Unique stocks', 'net_profit_direction' => 'Net Profit Direction', 'positive_negative_growth' => 'Positive / negative growth', 'highest_net_margin' => 'Highest Net Margin', 'lowest_debt_ratio' => 'Lowest Debt Ratio',
    'eps_coverage' => 'EPS Coverage', 'growth' => 'Growth', 'net_profit_growth' => 'Net Profit Growth', 'eps_growth' => 'EPS Growth',
    'period_types' => ['year' => 'Full Year', 'half_year' => 'Half Year', 'quarter' => 'Quarter', 'month' => 'Month', 'custom' => 'Custom',],
];
