<x-filament-panels::page>
    @php($stock = $record->stock)
    @php($metrics = ['revenue', 'gross_profit', 'net_profit', 'eps'])
    <div class="financial-report-print mx-auto max-w-7xl space-y-6">
        <section class="relative overflow-hidden rounded-2xl bg-gradient-to-br from-primary-600 via-primary-700 to-primary-900 p-6 shadow-lg sm:p-8">
            <div class="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-white/10"></div><div class="absolute -bottom-20 right-32 h-48 w-48 rounded-full border-[24px] border-white/10"></div>
            <div class="relative flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div class="flex items-center gap-4"><div class="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-white/15 text-xl font-bold tracking-wide text-white ring-1 ring-white/25">{{ $stock?->code ?? '—' }}</div><div><p class="mb-1 text-xs font-semibold uppercase tracking-[0.2em] text-primary-100">{{ __('financial_reports.financial_report') }}</p><h1 class="text-2xl font-bold text-white sm:text-3xl">{{ $stock?->name ?? __('financial_reports.stock') }}</h1>@if ($stock?->sector?->name_ar)<p class="mt-1 text-sm text-primary-100">{{ $stock->sector->name_ar }}</p>@endif</div></div><div class="flex flex-wrap gap-2"><x-filament::button color="white" icon="heroicon-o-arrow-down-tray" tag="a" :href="route('financial-reports.image', $record)" x-bind:href="'{{ route('financial-reports.image', $record) }}?theme=' + $store.theme">{{ __('financial_reports.download_image') }}</x-filament::button></div></div>
        </section>
        <section class="grid gap-4 md:grid-cols-2"><div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-900"><p class="text-xs font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">{{ __('financial_reports.base_period') }}</p><p class="mt-2 text-xl font-bold text-gray-950 dark:text-white">{{ $record->period_b_title }}</p><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ $record->period_b_type?->label() }}</p></div><div class="rounded-2xl border border-primary-200 bg-primary-50 p-5 shadow-sm dark:border-primary-800 dark:bg-primary-950/40"><p class="text-xs font-semibold uppercase tracking-wider text-primary-700 dark:text-primary-300">{{ __('financial_reports.current_period') }}</p><p class="mt-2 text-xl font-bold text-gray-950 dark:text-white">{{ $record->period_a_title }}</p><p class="mt-1 text-sm text-primary-700 dark:text-primary-300">{{ $record->period_a_type?->label() }}</p></div></section>
        <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-900"><div class="flex items-center justify-between border-b border-gray-200 px-5 py-4 dark:border-gray-700 sm:px-6"><div><h2 class="font-semibold text-gray-950 dark:text-white">{{ __('financial_reports.financial_metrics') }}</h2><p class="mt-0.5 text-sm text-gray-500 dark:text-gray-400">{{ $record->period_b_title }} → {{ $record->period_a_title }}</p></div>@if ($record->enable_projection)<span class="rounded-full bg-primary-100 px-3 py-1 text-xs font-semibold text-primary-700 dark:bg-primary-500/20 dark:text-primary-300">{{ __('financial_reports.projection') }} × {{ $record->projection_multiplier }}</span>@endif</div><div class="overflow-x-auto"><table class="min-w-full text-sm text-gray-700 dark:text-gray-200"><thead class="bg-gray-50 text-xs uppercase tracking-wider text-gray-500 dark:bg-gray-800/80 dark:text-gray-400"><tr><th class="px-5 py-3 text-start font-semibold sm:px-6">{{ __('financial_reports.item') }}</th><th class="px-5 py-3 text-end font-semibold">{{ $record->period_b_title }}</th><th class="px-5 py-3 text-end font-semibold">{{ $record->period_a_title }}</th><th class="px-5 py-3 text-end font-semibold">{{ __('financial_reports.coverage') }}</th><th class="px-5 py-3 text-end font-semibold">{{ __('financial_reports.growth') }}</th>@if($record->enable_projection)<th class="px-5 py-3 text-end font-semibold">{{ __('financial_reports.projected') }}</th>@endif</tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
        @foreach ($metrics as $metric) @php($coverage = $record->coverage($metric)) @php($growth = $record->growth($metric))<tr class="transition hover:bg-gray-50/80 dark:hover:bg-gray-800/50"><td class="px-5 py-5 sm:px-6"><p class="font-semibold text-gray-950 dark:text-white">{{ __('financial_reports.'.$metric) }}</p>@if($record->{"{$metric}_note"})<p class="mt-1.5 max-w-sm whitespace-pre-line text-xs leading-5 text-gray-500 dark:text-gray-400">{{ $record->{"{$metric}_note"} }}</p>@endif</td><td class="whitespace-nowrap px-5 py-5 text-end font-medium tabular-nums">{{ number_format((float) $record->{"{$metric}_b"}, 2) }}</td><td class="whitespace-nowrap px-5 py-5 text-end font-semibold tabular-nums text-gray-950 dark:text-white">{{ number_format((float) $record->{"{$metric}_a"}, 2) }}</td><td class="whitespace-nowrap px-5 py-5 text-end">@if($coverage !== null)<span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold {{ $coverage >= 100 ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300' }}">{{ number_format($coverage, 1) }}%</span>@else <span class="text-gray-400">—</span>@endif</td><td class="whitespace-nowrap px-5 py-5 text-end">@if($growth !== null)<span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold {{ $growth >= 0 ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-300' : 'bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-300' }}">{{ number_format($growth, 1) }}%</span>@else <span class="text-gray-400">—</span>@endif</td>@if($record->enable_projection)<td class="whitespace-nowrap px-5 py-5 text-end font-medium tabular-nums text-primary-700 dark:text-primary-300">{{ number_format((float) $record->projected($metric), 2) }}</td>@endif</tr>@endforeach
        </tbody></table></div></section>
        @if($record->summary_notes)<section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-900 sm:p-6"><div class="mb-5 flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-100 text-primary-700 dark:bg-primary-500/20 dark:text-primary-300"><x-filament::icon icon="heroicon-o-document-text" class="h-5 w-5" /></div><div><h2 class="font-semibold text-gray-950 dark:text-white">{{ __('financial_reports.summary_notes') }}</h2><p class="text-sm text-gray-500 dark:text-gray-400">{{ __('financial_reports.analyst_note') }}</p></div></div><div class="prose max-w-none text-gray-700 dark:prose-invert dark:text-gray-200">{!! $record->summary_notes !!}</div></section>@endif
    </div>
</x-filament-panels::page>
